apiVersion: apps/v1
kind: Deployment
metadata:
  name: sub-test
  labels:
    app: sub-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sub-test
  template:
    metadata:
      labels:
        app: sub-test
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "sub-test"
        dapr.io/app-port: "3313"
        dapr.io/sidecar-readiness-probe-delay-seconds: "60"
        dapr.io/log-level: "debug"
    spec:
      containers:
      - name: sub-test
        image: public.ecr.aws/m3s2c7t2/feindentity:sub
        ports:
        - containerPort: 3313
        imagePullPolicy: IfNotPresent