apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-publisher
  labels:
    app: user-publisher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-publisher
  template:
    metadata:
      labels:
        app: user-publisher
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "user-publisher"
        dapr.io/app-port: "3303"
        dapr.io/sidecar-readiness-probe-delay-seconds: "60"
        dapr.io/log-level: "debug"
    spec:
      containers:
      - name: user-publisher
        image: public.ecr.aws/m3s2c7t2/feindentity:pub-2
        ports:
        - containerPort: 3303
        imagePullPolicy: Always